### ISSUE TITLE
Option to create hyperlinks

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#100]
- [x] Should work with "http://" and without.
- [x] Should create link in current cursor positon. (inside of a table column, paragraph, list element)

**Comment by karl-p** [comment]
Use case:
> https://github.com/drozdik/Elephant/wiki/Detailed-Requirements#id-uc-100

**Comment by saaruniversity** [comment]
@karl-p 
Test

**Comment by karl-p** [comment]
Seems to work fine. Also, now you can insert hyperlink with empty text field. This way hyperlink's mask will be same as inserted URL.
