### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#131]
Ref #128 
> There is a documented procedure in place to build and deploy the prototype starting from a snapshot of the source code in the version control system. The procedure is reproducible. The build procedure is easy to use with minimal additional steps (for most teams it should be zero if we have not agreed otherwise up front).

**Comment by saaruniversity** [comment]
1. document must be
2. process must be
3. simple must be

Karl is responsible for it.

Also look non-functional requirements. For example there must be Gradle build.

**Comment by koppor** [comment]
See https://github.com/jusu/Elephant/issues/58

**Comment by saaruniversity** [comment]
Moved to "2.iteration - 1.week" milestone!

**Comment by koppor** [comment]
This is #117, isn't it?

**Comment by saaruniversity** [comment]
Ref #117 Non-functional requirement

**Comment by saaruniversity** [comment]
Took over.

**Comment by saaruniversity** [comment]
There are couple of things to improve in our current build process. @drozdik take over. You should be able to do it!

**Comment by drozdik** [comment]
'document must be' what kind of documentation we need from this issue? where to store?

**Comment by saaruniversity** [comment]
Basically description for a new inexperience person, how to get our code running locally, step by step guide, tutorial, with commands. That means everybody who reads our build documentation, is able to run the project.

Where to store? in wiki or in text file. Maybe you have previous experience with build documentation. How was it stored then?

**Comment by koppor** [comment]
I'm not sure whether I recommended looking at other projects such as [JabRef](https://github.com/JabRef/jabref/). When you open that URL, a rendered README.md appears showing what has to be done to get the thing running. Even if you think the description there could be improved, it shows that a `README.md` is the typical place for such an information.

**Comment by saaruniversity** [comment]
1. Give status update.
2. Look the build process's paragraph on site: https://courses.cs.ut.ee/2015/tvp/fall/Main/Third-iteration Is OK?
@drozdik

**Comment by drozdik** [comment]
Documentation added into README.md
