### ISSUE TITLE
Current code structure 

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#140]
Make flow charts, documentation for current Elephant's code structure and note editor.

Ref #129

**Comment by saaruniversity** [comment]
Moved to "2.iteration - 1.week" milestone!

**Comment by saaruniversity** [comment]
I gave it to Vladimir. It is connected with #139

**Comment by drozdik** [comment]
kui kaotab fookust:
konverdib MD html-ks, loob uus panel tulemusega (web view) ja asendab editor ala selle uue paneliga
saab fookust tagasi:
kustutab html paneli, asendab editor paneliga, kus on faili sisu (puhas MD)
koodis:
NoteEditor.java line:589 kovertimine html-ks
CustomEditor.java line: 957 asendamine html tava paneliga

**Comment by saaruniversity** [comment]
(y) Good, I will take this issue now over.

**Comment by saaruniversity** [comment]
Did small diagram. This was more what I was looking for. We should work through code and build something like that. I will keep improving it.

**Comment by saaruniversity** [comment]
This is constant issue, therefore, I will push it to 3.iteration.

**Comment by saaruniversity** [comment]
I will close this issue.
