### ISSUE TITLE
Testing process/environment/settings

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#153]
Setup for:
 - [x] Sikuli
 - [x] code coverage
..

Ref #118

**Comment by saaruniversity** [comment]
Changed label.

**Comment by saaruniversity** [comment]
University wants Sikuli.

**Comment by saaruniversity** [comment]
Ref #118 non-functional requirement

**Comment by saaruniversity** [comment]
1. Make Sikuli main class, that can be started manually.
2. Make some basic tests, so we know it is working.
3. Probably, you will be responsible for Sikuli during this course.
4. This setup should have been done last week, so we are in hurry! Because many new tasks are coming up

If any question, let me know! :)

**Comment by saaruniversity** [comment]
I will take over. It is connected with build process.  #131

**Comment by saaruniversity** [comment]
So basically we need two projects in our repo. One for Elephant and other for Sikuli. If you do not know what is Sikuli find out from last year Testing subject. 

Assign to @drozdik

**Comment by saaruniversity** [comment]
You can show your talent and get it done this week! 3.iteration-1.week. This task is necessary for our tester to work! @drozdik

**Comment by saaruniversity** [comment]
Give status update.
@drozdik

**Comment by drozdik** [comment]
CircleCi runs tests on master branch only. Project directory structure changed: main stuff moved into subdirectory 'Elephant', 'Sikuli' directory for testing added into project root.

**Comment by saaruniversity** [comment]
@taavi94 So is it working. Give status update.

**Comment by taavi94** [comment]
Sikuli tests are up, currently it tests issues #71 #72 #73 #74 #75 , @saaruniversity check to see if it works in your computer. I used SikulixIDE 1.1.0 to write them.

**Comment by taavi94** [comment]
Also i noticed that the note thumbnail doesn't show strikethrough format, but simply displays regular text, strikethrough does appear in the WYSIWYG mode.

**Comment by saaruniversity** [comment]
@karl-p  Please try running Sikuli tests in your computer. Ask introductions from Taavi.

**Comment by karl-p** [comment]
@saaruniversity Looks like it runs fine. It completed everything until to the point where updated button didn't match with test's picture (which was to be expected)

**Comment by saaruniversity** [comment]
ok thx. :)
