### ISSUE TITLE
Decide how we do push/pull

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#154]
Are we going to do new branch for each issue and then merge it with master?
Or ...

**Comment by saaruniversity** [comment]
Two options: 
 1. Branches for master, stable, development 
 1. One branch and then every new issue is pull request.

I prefer first option.

**Comment by koppor** [comment]
I agreed with @jusu to have one branch for each issue. This corresponds to the "feature branches" of http://nvie.com/posts/a-successful-git-branching-model/ (even though I don't fully agree with that model). The most important reason for that is that each improvement can be reviewed separately. See https://github.com/JabRef/jabref/pull/175 for an example.

I think, by "issue" you mean issues of your fork? Then this proposal is a mix of 1 and 2: For each issue at https://github.com/jusu/Elephant/issues, you should make a separate pull request.

I am aware that this causes more overhead. However, it is much more easiser to provide feedback and to have separation of concerns. In case pull requests don't go in fast enough into the upstream repository, we can discuss about switchting to another upstream repository.

You can surely have your own separate development branch for a full integration test.

Please focus on https://github.com/drozdik/Elephant/issues/131 as this is the basis for all future work. In case you need support with that, please contact me.

**Comment by saaruniversity** [comment]
Following branches:
1. Master
2. Develop
3. devusername_branch
4. issue

Flow will be following:

master < develop < devusername_branch < issue...

We will start with that flow. When coding gets going with higher speed, we can make adjustments and improvements.
