### ISSUE TITLE
Improve code review process

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#155]
Improve code review process

**Comment by koppor** [comment]
The final step is the customer:See  #154

Proposal:

* Create a seperate branch for adressing each issue of https://github.com/jusu/Elephant/issues. Let's call one `implement_issue_10`
* Each developer has his own branch `implement_issue_10_dev` and creates pull requests into the `implement_issue_10` branch. If the pull request is reviewed and agreed by someone else, a pull request of `implement_issue_10_dev` can be made into the upstream repository. 
* Then the customers review. If something needs to be adapted, it can be done in the `implement_issue_10_dev` branch with again a review of other team members.

Remarks:
* You can use `git rebase -i` and `git push -f` to bring the branch in a good shape before a pull request
* `[WIP]` as prefix of a pul request indicates that this is work in progress, comments welcome, but not ready to be merged

I did not cover how you integrate that with your development branch. Roughly speaking, you have to include each change from https://github.com/jusu/Elephant/ in your development branch. If you used `git rebase -i`, merging could be harder. Possilbly, you development branch has to be reset to https://github.com/jusu/Elephant/ from time to time.

**Comment by saaruniversity** [comment]
same as #154
