### ISSUE TITLE
UI wireframe/mockups 50%

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#158]
Ref #134 
50% of detailed requirements should be included

Note. ref #157 should be done before

**Comment by saaruniversity** [comment]
Karl,

1. You will get previous UI wireframe document from develop branch. 
2. Improve wireframe so that all use cases from #161 are there
3. Try to get document working. Currently there is only pdf. For some reason exporting document did not work for me. Used Evolus Pencil software.
4. If you have some additional comments about wireframe, add it to README file what is inside wireframe folder.
5. path: docs>wireframe
6. Currently we have wireframe wiki as well, not sure yet what should be there. You can think about it. Currently there is link to wireframe location.

If you have any questions, let me know!

**Comment by saaruniversity** [comment]
By document I meant that linking works. example "single web page"

**Comment by saaruniversity** [comment]
1) Make sure you also add search box, currently there is none. @karl-p

**Comment by karl-p** [comment]
I added use cases only to the main page. Some of the buttons that add an extra interface/window will open a new page, you can go back to previous page by clicking backspace or clicking the same button again if it is in the opened page (some of them don't have).

**Comment by saaruniversity** [comment]
Looks nice and neat (y) !
