### ISSUE TITLE
Black box testing for new updates

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#184]
#127 #126 #70 #69

Also you need to make test case documentation.

That means, what you tested and results. Like we did last year in testing subject.

**Comment by saaruniversity** [comment]
In develop branch. You can do black box testing.

**Comment by taavi94** [comment]
* When user clicks on another note, the note should be opened.
Created 2 notes, while was on second note I clicked on the first and the program opened it and showed the 

contents. Test successful
* Switching between two modes
Opened a note, i can type in it in plain text mode and WYSIWYG. Test successful
* Option to save
Created a new note, saved it as new.md by typing new.md in the title, the file saved automatically. Test successful
* When editor's text area is in focus, then typing on keyboard displays symbols in editor.
The program sowed symbols in both modes of editing when focused on text. Test Successful
