### ISSUE TITLE
EditorTools design

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#199]
Make buttons/labels beautiful.

All components are located in:
com.pinktwins.elephant.editor.EditorTools.java

The deadline is on Tuesday evening 8 pm, because on Wednesday we have intermediate demo!

We will get some more buttons there, but You should start working on that already! :)

pull from Develop branch

**Comment by saaruniversity** [comment]
Good that you did ! But let's improve that even more ! ;)

Remove background color, remove borders, make them smaller etc... Look please that picture that I sent you about Evernote. Let's put some more effort into it! :)

Also note that if there are more buttons then the panel fits, then these buttons disappear. 

This task must be done latest on Sunday! Because we have a lot more work to do.

**Comment by karl-p** [comment]
Things I'm done with:
* Bold (#63), italics (#89), underline (#90) and strikethrough (#91) buttons
* Switch mode button
* Font style (#87) and size (#88)drop down menu
* Show less/Show more button which hides/shows third line of buttons
* Text alignment buttons (#98)
* List buttons (#94, #95, #96, #97)

Things that are half way done:
* "Create table" button (#62) which right now opens menu with 10x10 buttons in grid layout. Need to add a function that focuses certain buttons in the grid.

**Comment by saaruniversity** [comment]
#74 make a button for that issue, strikethrough.

**Comment by karl-p** [comment]
* Finished "Create table" (#62)
* Added change text color (#92) and  highlight text (#93) buttons which open popup menu with 48 different color options

**Comment by karl-p** [comment]
Added #99, #100, #101, #109, #144 buttons. Also, changed layout of the buttons and added auto alignment to multiple rows.

**Comment by saaruniversity** [comment]
In the future table button should be expandable. That means it does not have default 10x10 grid, but the further a mouse cursor is moved, the more grid will be shown. 4th iteration.

**Comment by saaruniversity** [comment]
@karl-p 

#100 

Hyperlink button should ask for two fields. "name" "url". 

Make Hyperlink button separate class. If you do not know how, then you can get clues from TableButton, which is in separate class.

**Comment by saaruniversity** [comment]
Thx for work! :) I will move that task now to 4th iteration milestone.

**Comment by karl-p** [comment]
@saaruniversity I added popup menu to hyperlink button with 2 fields and 1 button. "Apply" button comes available once something is inserted into link (URL) field.

**Comment by saaruniversity** [comment]
I will close it for now.
