### ISSUE TITLE
Testing black box/junit/sikuli

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#202]
Testing for issues: 
#71 #72 #73 #74 #75

**Comment by saaruniversity** [comment]
If Sikuli's environment is not ready, then push Vladimir.

**Comment by saaruniversity** [comment]
Develop branch

**Comment by taavi94** [comment]
[Blackbox testing for Elephant.pdf](https://github.com/drozdik/Elephant/files/17587/Blackbox.testing.for.Elephant.pdf)

**Comment by saaruniversity** [comment]
See comment in #74 , about test case id 6.

**Comment by saaruniversity** [comment]
Good that you did some! :) But let's finish that task all.

JUnit and Sikuli tests are needed latest for Sunday!

**Comment by saaruniversity** [comment]
I will close this issue. Next time for new functionality issues we will not make separate task for testing. Instead, we will change assignee to tester.
