### ISSUE TITLE
EditorTools should not be enabled outside of .md files

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#228]
EditorTools should not be enabled in RTF files. First we will do it for .md files. Currently it just crashes program with rtf files.

- [x] Only in .md files should be enabled EditorTools.

**Comment by saaruniversity** [comment]
This is actually quite hard change, I spent quite a lot of time on it. Probably will move it to 4th iteration milestone.

**Comment by saaruniversity** [comment]
@karl-p 
Test

**Comment by karl-p** [comment]
Seems to work
