### ISSUE TITLE
Make functional requirement, backspacing

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#259]
Make functional requirement for #234 . 

- [x] Make a use case
- [x] Add into the requirements table
- [x] Add an update note, that we created a new requirement and a use case.

**Comment by karl-p** [comment]
Functional requirement can be found with the name "Deleting with backspace" [here] (https://github.com/drozdik/Elephant/wiki/First-Iteration---21.09.2015).

Use case can be found here [UC-234] (https://github.com/drozdik/Elephant/wiki/Detailed-Requirements#id-uc-234)
