### ISSUE TITLE
Make a new functional requirement, enter, wysi

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#260]
Make a new functional requirement, enter, wysi. Task #229 

- [x] Make a use case
- [x] Add into the requirements table
- [x] Add an update note, that we created a new requirement and a use case.

**Comment by karl-p** [comment]
Functional requirement can be found with the name "Enter has multiple usage" [here] (https://github.com/drozdik/Elephant/wiki/First-Iteration---21.09.2015). Couldn't find any better words to describe it.

Use case can be found here [UC-229] (https://github.com/drozdik/Elephant/wiki/Detailed-Requirements#id-uc-229)
