### ISSUE TITLE
Focus on click wysi

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#264]
Currently focus is gained only if it is clicked in certain areas. In wysi, there is a lot of white are, but clicking on it does not work. You have to click on the first empty row. This needs to be changed. It should work so that, when you switch it is already in focus and when you click on big white area it still should work.

Plus, if wysi switch mode button is clicked, it should focus also.

- [x] padding click should focus area, both modes.
- [x] switch mode should focus area, both modes

**Comment by saaruniversity** [comment]
@karl-p 
Test

**Comment by karl-p** [comment]
> padding click should focus area, both modes.
Can you elaborate what exactly this means? Clicking inside the "note text" field? If so then both seems to work fine. However, I noticed when gaining focus (without clicking on a specific line) in plain mode the blinking text cursor "|" is in the beginning of the note while in WYSIWYG mode it's in the end. Clicking on specific line works fine in both modes - it's in the end of the clicked line.
