### ISSUE TITLE
Two requirements are detailed

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#58]
Ref #7 

At least two of the functional requirements are detailed in the selected format (use case, specification,wireframes, ...).

https://courses.cs.ut.ee/2015/tvp/fall/Main/First-iteration

**Comment by karl-p** [comment]
https://docs.google.com/document/d/1qFBO9MopTjG7JkYBfbMH1jKBcUbSkYPZamrp7aBz1pE/edit?usp=sharing

**Comment by saaruniversity** [comment]
Good job!
Also one extra precondition: "WYSIWYG mode is enabled"
