### ISSUE TITLE
md syntax for strikethrough

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#74]

**Comment by saaruniversity** [comment]
Should work. But currently we are using <strike></strike>
So probably we must upgrade detailed requirements.

**Comment by saaruniversity** [comment]
Currently we are using
```
<strike></strike>
```
Customer wants that. But in GitHub md syntax also supports
```
~~that~~
```
So we need to make some decisions about requirements.

**Comment by saaruniversity** [comment]
So currently latest version in develop, has strikethrough syntax ~~ like in github's wiki. But we need a button for it also.

**Comment by saaruniversity** [comment]
My bad. md syntax does not need button. there is task #91

**Comment by saaruniversity** [comment]
@taavi94  test if works. Junit + blackbox + sikuli

**Comment by taavi94** [comment]
```
~~text~~ 
```
doesn't show strikethrough in thumbnail, it does however when i switch to wysiwyg mode in which thumbnail still doesn't show.
Html syntax for it works.

**Comment by saaruniversity** [comment]
For thumbnail view made new issue #249 

Thx for testing!
