### ISSUE TITLE
md syntax for unordered lists with indent

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#77]

**Comment by saaruniversity** [comment]
Second level must be with 4 spaces or tab. Does not work with one space like in GitHub.
Supports two levels.
Example:
- a 
    - a2
    - b2 
- b

**Comment by saaruniversity** [comment]
@taavi94 Test JUnit, Sikuli, black box. Develop branch.

**Comment by taavi94** [comment]
works

**Comment by saaruniversity** [comment]
Thx for testing!
