### ISSUE TITLE
md syntax for ordered lists with indent

### ISSUE THREAD

**Issue by saaruniversity** [drozdik/Elephant#79]

**Comment by saaruniversity** [comment]
Second level must be with 4 spaces or tab. Does not work with one space like in GitHub.
Supports two levels.
Example:
1. a 
    1. a2
    1. b2 
1. b

**Comment by saaruniversity** [comment]
@taavi94 Test JUnit, Sikuli, black box. Develop branch.

**Comment by taavi94** [comment]
works as @saaruniversity said with 4 spaces or tab

**Comment by saaruniversity** [comment]
Thx for testing!
